import { ArrowLeft, Loader2, ShieldAlert } from 'lucide-react';
import { useEffect, useState } from 'react';
import { GenesisCapApi, type FounderMetricsDto } from '../services/genesisCapApi';

function cap(value: string): string { return `${BigInt(value).toLocaleString()} CAP`; }
function growth(value: string | null): string { if (value === null) return 'No previous month'; const bps = BigInt(value); return `${bps >= 0n ? '+' : ''}${(Number(bps) / 100).toFixed(2)}% vs previous month`; }

export function FounderControlCenterPage({ onBack }: { onBack: () => void }) {
  const [metrics, setMetrics] = useState<FounderMetricsDto | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void GenesisCapApi.founderMetrics().then(setMetrics).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Metrics unavailable')); }, []);
  if (error) return <div className="page-stack"><button className="text-button" onClick={onBack}><ArrowLeft /> Wallet</button><section className="empty-state"><ShieldAlert /><h2>Founder access denied</h2><p>{error}. Access is enforced by the server-side verified-human allowlist.</p></section></div>;
  if (!metrics) return <section className="empty-state"><Loader2 className="spin" /><h2>Loading protected metrics</h2></section>;
  return <div className="page-stack founder-page"><button className="text-button" onClick={onBack}><ArrowLeft /> Wallet</button><div className="page-heading"><div><p className="eyebrow">Read-only privileged monitoring</p><h1>Founder Control Center</h1><p>Product, trust, CAP exposure, and growth operations. This surface has no mint, transfer, confiscation, winner, or payout controls.</p></div><span className="verified-pill">Server authorized</span></div>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Product</p><h2>Closed-beta activity</h2></div></div><div className="founder-grid"><article><small>Users</small><strong>{metrics.product.users}</strong></article><article><small>Verified humans</small><strong>{metrics.product.verifiedHumans}</strong></article><article><small>Titles issued</small><strong>{metrics.product.titlesIssued}</strong></article><article><small>Settled purchases</small><strong>{metrics.product.settledPurchases}</strong></article><article><small>Active campaign</small><strong>{metrics.product.activeCampaignId ?? 'None'}</strong></article><article><small>Monthly draw</small><strong>{metrics.product.monthlyDrawStatus ?? 'None'}</strong></article><article><small>Quarterly draw</small><strong>{metrics.product.quarterlyDrawStatus ?? 'None'}</strong></article></div></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Monthly Human Claim</p><h2>{metrics.humanClaim.period ?? 'No configured period'}</h2></div><span className="simulation-badge">{growth(metrics.humanClaim.participantGrowthBps)}</span></div><div className="founder-grid"><article><small>Fixed pool</small><strong>{cap(metrics.humanClaim.poolUnits)}</strong></article><article><small>Participants</small><strong>{metrics.humanClaim.participants}</strong></article><article><small>Previous month</small><strong>{metrics.humanClaim.previousPeriodParticipants}</strong></article><article><small>Exact settled/share</small><strong>{cap(metrics.humanClaim.settledUnitsPerHuman)}</strong></article><article><small>Total settled</small><strong>{cap(metrics.humanClaim.settledUnits)}</strong></article><article><small>Unissued</small><strong>{cap(metrics.humanClaim.unissuedUnits)}</strong></article></div><p className="estimate-line"><b>Projected CAP/share at 2× / 5× / 10× participants:</b> {cap(metrics.humanClaim.projectedShare2x)} / {cap(metrics.humanClaim.projectedShare5x)} / {cap(metrics.humanClaim.projectedShare10x)}. The fixed pool never expands with adoption.</p></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Genesis Growth</p><h2>{metrics.genesis.campaignId ?? 'No active campaign'}</h2></div></div><div className="founder-grid"><article><small>Budget</small><strong>{cap(metrics.genesis.budgetUnits)}</strong></article><article><small>Distributed</small><strong>{cap(metrics.genesis.distributedUnits)}</strong></article><article><small>Reserved</small><strong>{cap(metrics.genesis.reservedUnits)}</strong></article><article><small>Remaining</small><strong>{cap(metrics.genesis.remainingUnits)}</strong></article><article><small>Participants</small><strong>{metrics.genesis.participants}</strong></article><article><small>Verified referrals</small><strong>{metrics.genesis.verifiedReferrals}</strong></article><article><small>Milestones</small><strong>{metrics.genesis.milestoneQualifications}</strong></article><article><small>External pending</small><strong>{metrics.genesis.externalPending}</strong></article></div></section>
    {metrics.genesis.byQuest.length > 0 ? <section className="panel"><div className="section-heading"><div><p className="eyebrow">Quest consumption</p><h2>Published configuration performance</h2></div></div><div className="founder-grid">{metrics.genesis.byQuest.map((quest) => <article key={quest.questId}><small>{quest.questId}</small><strong>{quest.claimed} claimed</strong><span>{quest.qualified} qualified · {cap(quest.distributedUnits)}</span></article>)}</div></section> : null}
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">CAP source accounting</p><h2>Simulated, source-attributed ledger</h2></div><span className="simulation-badge">{metrics.cap.accountingMode}</span></div><div className="founder-grid"><article><small>Title entitlements</small><strong>{cap(metrics.cap.titleEntitlementUnits)}</strong></article><article><small>Human Claim</small><strong>{cap(metrics.cap.humanClaimUnits)}</strong></article><article><small>Genesis Growth</small><strong>{cap(metrics.cap.genesisGrowthUnits)}</strong></article><article><small>Available</small><strong>{cap(metrics.cap.availableUnits)}</strong></article><article><small>Locked</small><strong>{cap(metrics.cap.lockedUnits)}</strong></article><article><small>Total claimed</small><strong>{cap(metrics.cap.totalClaimedUnits)}</strong></article><article><small>Spent</small><strong>{cap(metrics.cap.spentUnits)}</strong></article><article><small>Burned</small><strong>{cap(metrics.cap.burnedUnits)}</strong></article></div></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Trust</p><h2>Latest draw evidence</h2></div><span className="simulation-badge">{metrics.trust.accountingMode}</span></div><div className="founder-grid"><article><small>Latest draw</small><strong>{metrics.trust.latestDrawId ?? 'None'}</strong></article><article><small>Manifest</small><strong>{metrics.trust.manifestCommitment ?? 'Not available'}</strong></article><article><small>Randomness</small><strong>{metrics.trust.randomnessStatus}</strong></article><article><small>External proof</small><strong>{metrics.trust.externalProofStatus}</strong></article><article><small>Anchor</small><strong>{metrics.trust.anchorStatus}</strong></article><article><small>Verify Draw</small><strong>{metrics.trust.verifyDrawStatus}</strong></article><article><small>Immutable CAP rows</small><strong>{metrics.trust.immutableLedgerRows}</strong></article><article><small>Production transfers</small><strong>NO</strong></article></div></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Operations</p><h2>Worker and readiness signals</h2></div></div><div className="founder-grid"><article><small>Reconciliation pending</small><strong>{metrics.operations.reconciliationPending}</strong></article><article><small>Failed / stuck payments</small><strong>{metrics.operations.reconciliationFailedOrStuck}</strong></article><article><small>Failed draw jobs</small><strong>{metrics.operations.drawJobsFailed}</strong></article><article><small>Readiness</small><strong>{metrics.operations.readinessStatus}</strong></article></div></section>
  </div>;
}
