import { ArrowLeft, Loader2, ShieldAlert } from 'lucide-react';
import { useEffect, useState } from 'react';
import { GenesisCapApi, type FounderMetricsDto } from '../services/genesisCapApi';

function cap(value: string): string { return `${BigInt(value).toLocaleString()} CAP`; }

export function FounderControlCenterPage({ onBack }: { onBack: () => void }) {
  const [metrics, setMetrics] = useState<FounderMetricsDto | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void GenesisCapApi.founderMetrics().then(setMetrics).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Metrics unavailable')); }, []);
  if (error) return <div className="page-stack"><button className="text-button" onClick={onBack}><ArrowLeft /> Wallet</button><section className="empty-state"><ShieldAlert /><h2>Founder access denied</h2><p>{error}. Access is enforced by the server-side verified-human allowlist.</p></section></div>;
  if (!metrics) return <section className="empty-state"><Loader2 className="spin" /><h2>Loading protected metrics</h2></section>;
  return <div className="page-stack founder-page"><button className="text-button" onClick={onBack}><ArrowLeft /> Wallet</button><div className="page-heading"><div><p className="eyebrow">Read-only privileged monitoring</p><h1>Founder Control Center</h1><p>Product, trust, CAP exposure, and growth operations. This surface has no mint, transfer, confiscation, winner, or payout controls.</p></div><span className="verified-pill">Server authorized</span></div>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Monthly Human Claim</p><h2>{metrics.humanClaim.period ?? 'No configured period'}</h2></div></div><div className="founder-grid"><article><small>Fixed pool</small><strong>{cap(metrics.humanClaim.poolUnits)}</strong></article><article><small>Participants</small><strong>{metrics.humanClaim.participants}</strong></article><article><small>Settled</small><strong>{cap(metrics.humanClaim.settledUnits)}</strong></article><article><small>Unissued</small><strong>{cap(metrics.humanClaim.unissuedUnits)}</strong></article></div><p className="estimate-line"><b>2× / 5× / 10× adoption</b> cannot exceed the fixed pool: {cap(metrics.humanClaim.projectedLiability2x)} / {cap(metrics.humanClaim.projectedLiability5x)} / {cap(metrics.humanClaim.projectedLiability10x)}.</p></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Genesis Growth</p><h2>{metrics.genesis.campaignId ?? 'No active campaign'}</h2></div></div><div className="founder-grid"><article><small>Budget</small><strong>{cap(metrics.genesis.budgetUnits)}</strong></article><article><small>Distributed</small><strong>{cap(metrics.genesis.distributedUnits)}</strong></article><article><small>Reserved</small><strong>{cap(metrics.genesis.reservedUnits)}</strong></article><article><small>Remaining</small><strong>{cap(metrics.genesis.remainingUnits)}</strong></article><article><small>Participants</small><strong>{metrics.genesis.participants}</strong></article><article><small>Verified referrals</small><strong>{metrics.genesis.verifiedReferrals}</strong></article><article><small>Milestones</small><strong>{metrics.genesis.milestoneQualifications}</strong></article><article><small>External pending</small><strong>{metrics.genesis.externalPending}</strong></article></div></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Trust operations</p><h2>Immutable source ledger</h2></div><span className="simulation-badge">{metrics.trust.accountingMode}</span></div><p>{metrics.trust.immutableLedgerRows} rows · production token transfers: NO</p></section>
  </div>;
}
