import { ArrowDownLeft, ArrowUpRight, CircleDollarSign, History, Landmark, ShieldAlert, WalletCards } from 'lucide-react';
import { useMvpStore, formatWld } from '../store/mvpStore';

function cap(value: string): string { return `${BigInt(value).toLocaleString()} $CAP`; }

export function WalletPage({ onOpenFounder }: { onOpenFounder: () => void }) {
  const { snapshot, journey } = useMvpStore();
  if (!snapshot || !journey) return <section className="empty-state"><h2>Wallet data unavailable</h2><p>WLD and $CAP accounting load from the server.</p></section>;
  const verifiedSpend = snapshot.ledger.filter((entry) => entry.classification === 'verified_purchase').reduce((sum, entry) => sum + BigInt(entry.amountUnits), 0n);
  const simulatedLiability = snapshot.ledger.filter((entry) => entry.classification === 'simulated_draw_prize').reduce((sum, entry) => sum + BigInt(entry.amountUnits), 0n);
  const demoVolume = snapshot.ledger.filter((entry) => entry.classification === 'demo_purchase').reduce((sum, entry) => sum + BigInt(entry.amountUnits), 0n);
  return <div className="page-stack">
    <div className="page-heading"><div><p className="eyebrow">WLD + $CAP source accounting</p><h1>Wallet & history</h1><p>Verified WLD spend, simulated prize liabilities, and source-attributed $CAP remain separate.</p></div><button className="text-button" onClick={onOpenFounder}>Founder access</button></div>
    <section className="wallet-card"><div className="wallet-orb"><WalletCards /></div><div><small>Connected payer</small><h2 className="wallet-address">{snapshot.walletAddress ? `${snapshot.walletAddress.slice(0, 8)}…${snapshot.walletAddress.slice(-6)}` : 'No verified payment yet'}</h2><p>No custodial or invented in-app WLD balance</p></div><div className="wallet-actions"><button disabled><ArrowDownLeft size={17} /> Add WLD</button><button disabled><ArrowUpRight size={17} /> Send</button></div></section>
    <section className="panel cap-hub"><div className="section-heading"><div><p className="eyebrow">$CAP hub</p><h2>{cap(journey.cap.availableUnits)} available</h2></div><span className="simulation-badge">Simulated · non-on-chain</span></div><div className="cap-source-grid"><article><small>Title entitlement</small><strong>{cap(journey.cap.titleEntitlementUnits)}</strong></article><article><small>Human Claim</small><strong>{cap(journey.cap.humanClaimUnits)}</strong></article><article><small>Genesis Growth</small><strong>{cap(journey.cap.genesisGrowthUnits)}</strong></article><article><small>Locked</small><strong>{cap(journey.cap.lockedUnits)}</strong></article><article><small>Spent</small><strong>{cap(journey.cap.spentUnits)}</strong></article><article><small>Burned</small><strong>{cap(journey.cap.burnedUnits)}</strong></article></div></section>
    <section className="wallet-stat-grid"><article><span><CircleDollarSign /></span><small>Verified WLD spent</small><strong>{formatWld(verifiedSpend)}</strong></article><article><span><ShieldAlert /></span><small>Simulated draw liabilities</small><strong>{formatWld(simulatedLiability)}</strong></article><article><span><Landmark /></span><small>Quarterly allocation</small><strong>{formatWld(snapshot.pools.quarterly_jackpot)}</strong></article></section>
    <section className="panel history-panel"><div className="section-heading"><div><p className="eyebrow">WLD ledger</p><h2>Activity</h2></div><History size={20} /></div><div className="ledger-list">{snapshot.ledger.length ? snapshot.ledger.map((entry) => <article key={entry.id}><span className={`ledger-icon ${entry.direction}`}>{entry.direction === 'credit' ? <ArrowDownLeft /> : <ArrowUpRight />}</span><div><b>{entry.description}</b><small>{entry.classification === 'verified_purchase' ? 'Verified purchase' : entry.classification === 'demo_purchase' ? 'Demo · no WLD moved' : 'Simulated · non-spendable'} · {new Date(entry.createdAt).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}</small></div><strong className={entry.direction}>{entry.direction === 'credit' ? '+' : '-'}{formatWld(entry.amountUnits)}</strong></article>) : <p className="empty-ledger">No economic activity yet.</p>}</div></section>
    {demoVolume > 0n ? <section className="legal-notice"><ShieldAlert size={18} /><p><b>{formatWld(demoVolume)} is demo acquisition volume, not verified WLD spend.</b> No payment moved and it is never spendable.</p></section> : null}
    <section className="legal-notice"><ShieldAlert size={18} /><p><b>Technical beta is not authorized for real-money prize settlement.</b> $CAP is simulated/non-on-chain and draw liabilities are non-spendable.</p></section>
  </div>;
}
